// This file is auto-generated by scripts/generate-built-in-preset-ids.mjs
// Do not edit manually.

export const builtInPresetIds = [
  "amber-minimal",
  "amethyst-haze",
  "bold-tech",
  "clean-slate",
  "cosmic-night",
  "doom-64",
  "elegant-luxury",
  "kodama-grove",
  "midnight-bloom",
  "mocha-mousse",
  "modern-minimal",
  "neo-brutalism",
  "northern-lights",
  "ocean-breeze",
  "pastel-dreams",
  "quantum-rose",
  "retro-arcade",
  "soft-pop",
  "solar-dusk",
  "starry-night",
  "sunset-horizon",
  "t3-chat",
  "vintage-paper",
  "violet-bloom",
] as const;

export type BuiltInPresetId = (typeof builtInPresetIds)[number];
